modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="bios_wrath_weapons"
version="1.0.0"
displayName="Bio's Wrath Weapons"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bioscar, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bios_wrath_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.bios_wrath_weapons]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bios_wrath_weapons]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration